modLoader="javafml"
loaderVersion="[38,)"
license="LGPL-3.0-or-later"
logoFile="elytrautilities_icon.png"
logoBlur=false
[[mods]]
modId="elytrautilities"
version="${version}"
displayName="Elytra Utilities"
authors="C4"
description='''
A small collection of useful elytra controls such as easy takeoff and enabling/disabling elytras.
'''
[[dependencies.elytrautilities]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elytrautilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
